################################################
## Packages / Waste
################################################
homeassistant:
  customize:
    sensor.afvalwijzer_today:
      friendly_name: Vandaag
    sensor.afvalwijzer_tomorrow:
      friendly_name: Morgen
    sensor.afvalwijzer_next_item:
      friendly_name: Next pickup item
    sensor.afvalwijzer_next_in_days:
      friendly_name: Next pickup in days
    input_boolean.waste_reminder:
      icon: mdi:reminder

    sensor.avri_afvalbeheer_gft:
      friendly_name: GFT
      entity_picture: \local\images\afvalbeheer\gft.png
    sensor.avri_afvalbeheer_papier:
      friendly_name: Papier
      entity_picture: \local\images\afvalbeheer\papier.png
    sensor.avri_afvalbeheer_pmd:
      friendly_name: PMD
      entity_picture: \local\images\afvalbeheer\pmd.png

################################################
## Inputs
################################################
input_boolean:
  waste_moved:
    name: Waste has been moved
    initial: off
    icon: mdi:delete-empty
  waste_reminder:
    name: Waste reminder enabled
    initial: on

################################################
## Sensor
################################################

sensor:
  - platform: afvalbeheer
    wastecollector: Avri
    resources:
      - pmd
      - gft
      - papier
    postcode: !secret Home_PostalCode
    streetnumber: !secret Home_StreetNumber
    upcomingsensor: 1
    dateformat: "%d %b"
    printwastetypes: 0
    dateonly: 0
    dayofweek: 1
    alwaysshowday: 1
    dateobject: 0
    name: "Afvalbeheer"
    nameprefix: 1
    builtinicons: 0
    disableicons: 0
    dutch: 1

    # default_label: 'Geen'
  - platform: template
    sensors:
      avri_today_formatted:
        value_template: >-
          {% if is_state('sensor.avri_afvalbeheer_vandaag', 'gft') %}GFT
          {% elif is_state('sensor.avri_afvalbeheer_vandaag', 'papier') %}Papier
          {% elif is_state('sensor.avri_afvalbeheer_vandaag', 'pmd') %}PMD
          {% else %}Geen
          {% endif %}
        friendly_name: "Vandaag"

      avri_tomorrow_formatted:
        value_template: >-
          {% if is_state('sensor.avri_afvalbeheer_morgen', 'gft') %}GFT
          {% elif is_state('sensor.avri_afvalbeheer_morgen', 'papier') %}Papier
          {% elif is_state('sensor.avri_afvalbeheer_morgen', 'pmd') %}PMD
          {% else %}Geen
          {% endif %}
        friendly_name: "Morgen"
################################################
## Automation
################################################
